### Install datasets library

!uv add datasets

In [25]:
from datasets import load_dataset

### Load a dataset

In [26]:
dataset = load_dataset("stanfordnlp/imdb")

print(dataset)

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    test: Dataset({
        features: ['text', 'label'],
        num_rows: 25000
    })
    unsupervised: Dataset({
        features: ['text', 'label'],
        num_rows: 50000
    })
})

### Access a split

In [27]:
train_dataset = dataset["train"]
test_dataset = dataset["test"]

In [28]:
import pandas as pd

pd.DataFrame(train_dataset)

                                                    text  label
0      I rented I AM CURIOUS-YELLOW from my video sto...      0
1      "I Am Curious: Yellow" is a risible and preten...      0
2      If only to avoid making this type of film in t...      0
3      This film was probably inspired by Godard's Ma...      0
4      Oh, brother...after hearing about this ridicul...      0
...                                                  ...    ...
24995  A hit at the time but now better categorised a...      1
24996  I love this movie like no other. Another time ...      1
24997  This film and it's sequel Barry Mckenzie holds...      1
24998  'The Adventures Of Barry McKenzie' started lif...      1
24999  The story centers around Barry McKenzie who mu...      1

[25000 rows x 2 columns]

In [29]:
pd.DataFrame(test_dataset)

                                                    text  label
0      I love sci-fi and am willing to put up with a ...      0
1      Worth the entertainment value of a rental, esp...      0
2      its a totally average film with a few semi-alr...      0
3      STAR RATING: ***** Saturday Night **** Friday ...      0
4      First off let me say, If you haven't enjoyed a...      0
...                                                  ...    ...
24995  Just got around to seeing Monster Man yesterda...      1
24996  I got this as part of a competition prize. I w...      1
24997  I got Monster Man in a box set of three films ...      1
24998  Five minutes in, i started to feel how naff th...      1
24999  I caught this movie on the Sci-Fi channel rece...      1

[25000 rows x 2 columns]

In [5]:
print(len(train_dataset))
print(len(test_dataset))

25000
25000

In [7]:
# look at one example

example = train_dataset[0]

print(example)

{'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it\'s not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn\'t have much of a plot.', 'label': 0}

In [10]:
# get the first review
print(train_dataset[0]["text"])

I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it's not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn't have much of a plot.

In [11]:
# get the labels
print(train_dataset[0]["label"])

0

In [30]:
# retrieve multiple examples
from pprint import pprint

pprint(train_dataset[:5])

{'label': [0, 0, 0, 0, 0],
 'text': ['I rented I AM CURIOUS-YELLOW from my video store because of all the '
          'controversy that surrounded it when it was first released in 1967. '
          'I also heard that at first it was seized by U.S. customs if it ever '
          'tried to enter this country, therefore being a fan of films '
          'considered "controversial" I really had to see this for myself.<br '
          '/><br />The plot is centered around a young Swedish drama student '
          'named Lena who wants to learn everything she can about life. In '
          'particular she wants to focus her attentions to making some sort of '
          'documentary on what the average Swede thought about certain '
          'political issues such as the Vietnam War and race issues in the '
          'United States. In between asking politicians and ordinary denizens '
          'of Stockholm about their opinions on politics, she has sex with her '
          'drama teacher, classmates, and married men.<br /><br />What kills '
          'me about I AM CURIOUS-YELLOW is that 40 years ago, this was '
          'considered pornographic. Really, the sex and nudity scenes are few '
          "and far between, even then it's not shot like some cheaply made "
          'porno. While my countrymen mind find it shocking, in reality sex '
          'and nudity are a major staple in Swedish cinema. Even Ingmar '
          'Bergman, arguably their answer to good old boy John Ford, had sex '
          'scenes in his films.<br /><br />I do commend the filmmakers for the '
          'fact that any sex shown in the film is shown for artistic purposes '
          'rather than just to shock people and make money to be shown in '
          'pornographic theaters in America. I AM CURIOUS-YELLOW is a good '
          'film for anyone wanting to study the meat and potatoes (no pun '
          "intended) of Swedish cinema. But really, this film doesn't have "
          'much of a plot.',
          '"I Am Curious: Yellow" is a risible and pretentious steaming pile. '
          "It doesn't matter what one's political views are because this film "
          'can hardly be taken seriously on any level. As for the claim that '
          "frontal male nudity is an automatic NC-17, that isn't true. I've "
          'seen R-rated films with male nudity. Granted, they only offer some '
          'fleeting views, but where are the R-rated films with gaping vulvas '
          "and flapping labia? Nowhere, because they don't exist. The same "
          'goes for those crappy cable shows: schlongs swinging in the breeze '
          'but not a clitoris in sight. And those pretentious indie movies '
          "like The Brown Bunny, in which we're treated to the site of Vincent "
          "Gallo's throbbing johnson, but not a trace of pink visible on Chloe "
          'Sevigny. Before crying (or implying) "double-standard" in matters '
          'of nudity, the mentally obtuse should take into account one '
          'unavoidably obvious anatomical difference between men and women: '
          'there are no genitals on display when actresses appears nude, and '
          "the same cannot be said for a man. In fact, you generally won't see "
          'female genitals in an American film in anything short of porn or '
          'explicit erotica. This alleged double-standard is less a double '
          'standard than an admittedly depressing ability to come to terms '
          "culturally with the insides of women's bodies.",
          'If only to avoid making this type of film in the future. This film '
          'is interesting as an experiment but tells no cogent story.<br /><br '
          '/>One might feel virtuous for sitting thru it because it touches on '
          'so many IMPORTANT issues but it does so without any discernable '
          'motive. The viewer comes away with no new perspectives (unless one '
          "comes up with one while one's mind wanders, as it will invariably "
          'do during this pointless film).<br /><br />One might better spend '
          "one's time staring out a window at a tree growing.<br /><br />",
          "This film was probably inspired by Godard's Masculin, féminin and I "
          'urge you to see that film instead.<br /><br />The film has two '
          'strong elements and those are, (1) the realistic acting (2) the '
          'impressive, undeservedly good, photo. Apart from that, what strikes '
          'me most is the endless stream of silliness. Lena Nyman has to be '
          'most annoying actress in the world. She acts so stupid and with all '
          "the nudity in this film,...it's unattractive. Comparing to Godard's "
          'film, intellectuality has been replaced with stupidity. Without '
          'going too far on this subject, I would say that follows from the '
          'difference in ideals between the French and the Swedish society.<br '
          '/><br />A movie of its time, and place. 2/10.',
          'Oh, brother...after hearing about this ridiculous film for umpteen '
          'years all I can think of is that old Peggy Lee song..<br /><br '
          '/>"Is that all there is??" ...I was just an early teen when this '
          'smoked fish hit the U.S. I was too young to get in the theater '
          '(although I did manage to sneak into "Goodbye Columbus"). Then a '
          'screening at a local film museum beckoned - Finally I could see '
          'this film, except now I was as old as my parents were when they '
          'schlepped to see it!!<br /><br />The ONLY reason this film was not '
          'condemned to the anonymous sands of time was because of the '
          'obscenity case sparked by its U.S. release. MILLIONS of people '
          'flocked to this stinker, thinking they were going to see a sex '
          'film...Instead, they got lots of closeups of gnarly, repulsive '
          'Swedes, on-street interviews in bland shopping malls, asinie '
          'political pretension...and feeble who-cares simulated sex scenes '
          'with saggy, pale actors.<br /><br />Cultural icon, holy grail, '
          'historic artifact..whatever this thing was, shred it, burn it, then '
          'stuff the ashes in a lead box!<br /><br />Elite esthetes still '
          'scrape to find value in its boring pseudo revolutionary political '
          "spewings..But if it weren't for the censorship scandal, it would "
          'have been ignored, then forgotten.<br /><br />Instead, the "I Am '
          'Blank, Blank" rhythymed title was repeated endlessly for years as a '
          'titilation for porno films (I am Curious, Lavender - for gay films, '
          'I Am Curious, Black - for blaxploitation films, etc..) and every '
          'ten years or so the thing rises from the dead, to be viewed by a '
          'new generation of suckers who want to see that "naughty sex film" '
          'that "revolutionized the film industry"...<br /><br />Yeesh, avoid '
          'like the plague..Or if you MUST see it - rent the video and fast '
          'forward to the "dirty" parts, just to get it over with.<br /><br '
          '/>']}

### Get a smaller dataset

In [13]:
small_dataset = train_dataset.select(range(100))

print(len(small_dataset))

100

## Upload Dataset to Huggingface

In [31]:
import pandas as pd

df = pd.DataFrame({
    "text": [
        "I love Python",
        "Python is easy to learn",
        "I don't like bugs"
    ],
    "label": [
        1,
        1,
        0
    ]
})

print(df)

                      text  label
0            I love Python      1
1  Python is easy to learn      1
2        I don't like bugs      0

In [32]:
from datasets import Dataset

# -------------------------
# DataFrame -> HF Dataset
# -------------------------
dataset = Dataset.from_pandas(df)

print(dataset)

Dataset({
    features: ['text', 'label'],
    num_rows: 3
})

## Push dataset to hub

In [33]:
dataset.push_to_hub(repo_id="worldboss/my-dataset", split="train")

Setting num_proc from 1 back to 1 for the train split to disable multiprocessing as it only contains one shard.
Creating parquet from Arrow format: 100%|██████████| 1/1 [00:00<00:00, 61.55ba/s]
Processing Files (1 / 1): 100%|██████████| 1.39kB / 1.39kB,   ???B/s
New Data Upload: |          |  0.00B /  0.00B,   ???B/s
Uploading the dataset shards: 100%|██████████| 1/1 [00:01<00:00,  1.55s/ shards]

CommitInfo(commit_url='https://huggingface.co/datasets/worldboss/my-dataset/commit/72d7eeaddb31b0d3c2f1ba64a5f6c9da3fa43d44', commit_message='Upload dataset', commit_description='', oid='72d7eeaddb31b0d3c2f1ba64a5f6c9da3fa43d44', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/worldboss/my-dataset', endpoint='https://huggingface.co', repo_type='dataset', repo_id='worldboss/my-dataset'), pr_revision=None, pr_num=None)

In [34]:
from datasets import load_dataset

dataset = load_dataset("worldboss/my-dataset")

print(dataset)

Generating train split: 100%|██████████| 3/3 [00:00<00:00, 11.38 examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 3
    })
})

## Load .csv file

In [36]:
df = pd.read_csv("lauki_qna.csv")

df.head()

,question,answer
0,What plans do Lauki Phones offer?,"Prepaid, postpaid, family, enterprise, and dat..."
1,How do I activate a new SIM?,"Insert the SIM, complete KYC with government-i..."
2,How long does activation take?,Activation completes within 30 minutes in most...
3,Does Lauki Phones support eSIM?,Supported on devices that follow GSMA eSIM sta...
4,How do I switch from physical SIM to eSIM?,"Authenticate in the portal, request conversion..."

In [37]:
# save it as json or jsonl file 
df.to_json("lauki_qna.jsonl", orient="records", lines=True)

df.to_json("lauki_qna.json", orient="records", indent=2)

In [38]:
from datasets import Dataset
from datasets import load_dataset

dataset = Dataset.from_pandas(df, preserve_index=False)

# For LLM/ML datasets, I'd generally recommend JSONL:
dataset.to_json("my-dataset.jsonl")

Creating json from Arrow format: 100%|██████████| 1/1 [00:00<00:00,  4.56ba/s]

27311

In [24]:
dataset = load_dataset("stanfordnlp/imdb", split="train")

# For LLM/ML datasets, I'd generally recommend JSONL:
dataset.to_json("my-dataset.jsonl")

Creating json from Arrow format: 100%|██████████| 25/25 [00:00<00:00, 46.98ba/s]

33880437

### Load a specific dataset split

In [39]:
train_dataset = load_dataset("stanfordnlp/imdb", split="train")

print(train_dataset)

Dataset({
    features: ['text', 'label'],
    num_rows: 25000
})

### Load a dataset for Qwen3

In [40]:
from datasets import load_dataset
from transformers import AutoTokenizer

dataset = load_dataset("stanfordnlp/imdb")

tokenizer = AutoTokenizer.from_pretrained("Qwen/Qwen3-0.6B")

In [41]:
example = dataset["train"][0]

print(example["text"])

I rented I AM CURIOUS-YELLOW from my video store because of all the controversy that surrounded it when it was first released in 1967. I also heard that at first it was seized by U.S. customs if it ever tried to enter this country, therefore being a fan of films considered "controversial" I really had to see this for myself.<br /><br />The plot is centered around a young Swedish drama student named Lena who wants to learn everything she can about life. In particular she wants to focus her attentions to making some sort of documentary on what the average Swede thought about certain political issues such as the Vietnam War and race issues in the United States. In between asking politicians and ordinary denizens of Stockholm about their opinions on politics, she has sex with her drama teacher, classmates, and married men.<br /><br />What kills me about I AM CURIOUS-YELLOW is that 40 years ago, this was considered pornographic. Really, the sex and nudity scenes are few and far between, even then it's not shot like some cheaply made porno. While my countrymen mind find it shocking, in reality sex and nudity are a major staple in Swedish cinema. Even Ingmar Bergman, arguably their answer to good old boy John Ford, had sex scenes in his films.<br /><br />I do commend the filmmakers for the fact that any sex shown in the film is shown for artistic purposes rather than just to shock people and make money to be shown in pornographic theaters in America. I AM CURIOUS-YELLOW is a good film for anyone wanting to study the meat and potatoes (no pun intended) of Swedish cinema. But really, this film doesn't have much of a plot.

In [20]:
# tokenize it

tokens = tokenizer(example["text"])

print(tokens)

{'input_ids': [40, 48859, 358, 6769, 18548, 42652, 29137, 34671, 504, 847, 2766, 3553, 1576, 315, 678, 279, 25573, 429, 22865, 432, 979, 432, 572, 1156, 5880, 304, 220, 16, 24, 21, 22, 13, 358, 1083, 6617, 429, 518, 1156, 432, 572, 30489, 553, 547, 808, 13, 34769, 421, 432, 3512, 6679, 311, 3725, 419, 3146, 11, 8916, 1660, 264, 8405, 315, 12351, 6509, 330, 772, 12563, 530, 1, 358, 2167, 1030, 311, 1490, 419, 369, 7037, 15757, 1323, 23976, 1323, 6206, 785, 7089, 374, 30188, 2163, 264, 3908, 30109, 19584, 5458, 6941, 81062, 879, 6801, 311, 3960, 4297, 1340, 646, 911, 2272, 13, 758, 3953, 1340, 6801, 311, 5244, 1059, 51209, 908, 311, 3259, 1045, 3378, 315, 24954, 389, 1128, 279, 5461, 4492, 15326, 3381, 911, 3654, 4948, 4714, 1741, 438, 279, 22500, 5004, 323, 6957, 4714, 304, 279, 3639, 4180, 13, 758, 1948, 10161, 18761, 323, 19119, 3371, 28960, 315, 52082, 911, 862, 17979, 389, 11500, 11, 1340, 702, 1839, 448, 1059, 19584, 11079, 11, 60090, 11, 323, 12224, 2953, 15757, 1323, 23976, 1323, 6206, 3838, 28810, 752, 911, 358, 6769, 18548, 42652, 29137, 34671, 374, 429, 220, 19, 15, 1635, 4134, 11, 419, 572, 6509, 3480, 12679, 13, 28208, 11, 279, 1839, 323, 91372, 16065, 525, 2421, 323, 3041, 1948, 11, 1496, 1221, 432, 594, 537, 6552, 1075, 1045, 11872, 398, 1865, 5850, 13, 5976, 847, 3146, 5676, 3971, 1477, 432, 33634, 11, 304, 8729, 1839, 323, 91372, 525, 264, 3598, 48956, 304, 30109, 33192, 13, 7418, 24871, 5612, 30682, 1515, 11, 35559, 862, 4226, 311, 1661, 2310, 8171, 3757, 14010, 11, 1030, 1839, 16065, 304, 806, 12351, 15757, 1323, 23976, 1323, 6206, 40, 653, 73112, 279, 62103, 369, 279, 2097, 429, 894, 1839, 6839, 304, 279, 4531, 374, 6839, 369, 31592, 9895, 4751, 1091, 1101, 311, 10755, 1251, 323, 1281, 3220, 311, 387, 6839, 304, 3480, 12679, 43766, 304, 5159, 13, 358, 6769, 18548, 42652, 29137, 34671, 374, 264, 1661, 4531, 369, 5489, 19211, 311, 3920, 279, 13041, 323, 34167, 320, 2152, 8310, 10602, 8, 315, 30109, 33192, 13, 1988, 2167, 11, 419, 4531, 3171, 944, 614, 1753, 315, 264, 7089, 13], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

### Tokenize the entire dataset

In [42]:
def tokenize_function(example):
    return tokenizer(example["text"], truncation=True, max_length=512)

In [45]:
def to_upper(word: str):
    return word.upper()

list(map(to_upper, ["hello", "world"]))

['HELLO', 'WORLD']

In [51]:
list(map(lambda word: word.upper(), ["hello", "world"]))

['HELLO', 'WORLD']

In [47]:
tokenized_dataset = dataset.map(tokenize_function, batched=True)

{
    "text": "...",
    "label": 1,
    "input_ids": [...],
    "attention_mask": [...]
}

In [48]:
pprint(tokenized_dataset["train"][0])

{'attention_mask': [1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1,
                    1],
 'input_ids': [40,
               48859,
               358,
               6769,
               18548,
               42652,
               29137,
               34671,
               504,
               847,
               2766,
               3553,
               1576,
               315,
               678,
               279,
               25573,
               429,
               22865,
               432,
               979,
               432,
               572,
               1156,
               5880,
               304,
               220,
               16,
               24,
               21,
               22,
               13,
               358,
               1083,
               6617,
               429,
               518,
               1156,
               432,
               572,
               30489,
               553,
               547,
               808,
               13,
               34769,
               421,
               432,
               3512,
               6679,
               311,
               3725,
               419,
               3146,
               11,
               8916,
               1660,
               264,
               8405,
               315,
               12351,
               6509,
               330,
               772,
               12563,
               530,
               1,
               358,
               2167,
               1030,
               311,
               1490,
               419,
               369,
               7037,
               15757,
               1323,
               23976,
               1323,
               6206,
               785,
               7089,
               374,
               30188,
               2163,
               264,
               3908,
               30109,
               19584,
               5458,
               6941,
               81062,
               879,
               6801,
               311,
               3960,
               4297,
               1340,
               646,
               911,
               2272,
               13,
               758,
               3953,
               1340,
               6801,
               311,
               5244,
               1059,
               51209,
               908,
               311,
               3259,
               1045,
               3378,
               315,
               24954,
               389,
               1128,
               279,
               5461,
               4492,
               15326,
               3381,
               911,
               3654,
               4948,
               4714,
               1741,
               438,
               279,
               22500,
               5004,
               323,
               6957,
               4714,
               304,
               279,
               3639,
               4180,
               13,
               758,
               1948,
               10161,
               18761,
               323,
               19119,
               3371,
               28960,
               315,
               52082,
               911,
               862,
               17979,
               389,
               11500,
               11,
               1340,
               702,
               1839,
               448,
               1059,
               19584,
               11079,
               11,
               60090,
               11,
               323,
               12224,
               2953,
               15757,
               1323,
               23976,
               1323,
               6206,
               3838,
               28810,
               752,
               911,
               358,
               6769,
               18548,
               42652,
               29137,
               34671,
               374,
               429,
               220,
               19,
               15,
               1635,
               4134,
               11,
               419,
               572,
               6509,
               3480,
               12679,
               13,
               28208,
               11,
               279,
               1839,
               323,
               91372,
               16065,
               525,
               2421,
               323,
               3041,
               1948,
               11,
               1496,
               1221,
               432,
               594,
               537,
               6552,
               1075,
               1045,
               11872,
               398,
               1865,
               5850,
               13,
               5976,
               847,
               3146,
               5676,
               3971,
               1477,
               432,
               33634,
               11,
               304,
               8729,
               1839,
               323,
               91372,
               525,
               264,
               3598,
               48956,
               304,
               30109,
               33192,
               13,
               7418,
               24871,
               5612,
               30682,
               1515,
               11,
               35559,
               862,
               4226,
               311,
               1661,
               2310,
               8171,
               3757,
               14010,
               11,
               1030,
               1839,
               16065,
               304,
               806,
               12351,
               15757,
               1323,
               23976,
               1323,
               6206,
               40,
               653,
               73112,
               279,
               62103,
               369,
               279,
               2097,
               429,
               894,
               1839,
               6839,
               304,
               279,
               4531,
               374,
               6839,
               369,
               31592,
               9895,
               4751,
               1091,
               1101,
               311,
               10755,
               1251,
               323,
               1281,
               3220,
               311,
               387,
               6839,
               304,
               3480,
               12679,
               43766,
               304,
               5159,
               13,
               358,
               6769,
               18548,
               42652,
               29137,
               34671,
               374,
               264,
               1661,
               4531,
               369,
               5489,
               19211,
               311,
               3920,
               279,
               13041,
               323,
               34167,
               320,
               2152,
               8310,
               10602,
               8,
               315,
               30109,
               33192,
               13,
               1988,
               2167,
               11,
               419,
               4531,
               3171,
               944,
               614,
               1753,
               315,
               264,
               7089,
               13],
 'label': 0,
 'text': 'I rented I AM CURIOUS-YELLOW from my video store because of all the '
         'controversy that surrounded it when it was first released in 1967. I '
         'also heard that at first it was seized by U.S. customs if it ever '
         'tried to enter this country, therefore being a fan of films '
         'considered "controversial" I really had to see this for myself.<br '
         '/><br />The plot is centered around a young Swedish drama student '
         'named Lena who wants to learn everything she can about life. In '
         'particular she wants to focus her attentions to making some sort of '
         'documentary on what the average Swede thought about certain '
         'political issues such as the Vietnam War and race issues in the '
         'United States. In between asking politicians and ordinary denizens '
         'of Stockholm about their opinions on politics, she has sex with her '
         'drama teacher, classmates, and married men.<br /><br />What kills me '
         'about I AM CURIOUS-YELLOW is that 40 years ago, this was considered '
         'pornographic. Really, the sex and nudity scenes are few and far '
         "between, even then it's not shot like some cheaply made porno. While "
         'my countrymen mind find it shocking, in reality sex and nudity are a '
         'major staple in Swedish cinema. Even Ingmar Bergman, arguably their '
         'answer to good old boy John Ford, had sex scenes in his films.<br '
         '/><br />I do commend the filmmakers for the fact that any sex shown '
         'in the film is shown for artistic purposes rather than just to shock '
         'people and make money to be shown in pornographic theaters in '
         'America. I AM CURIOUS-YELLOW is a good film for anyone wanting to '
         'study the meat and potatoes (no pun intended) of Swedish cinema. But '
         "really, this film doesn't have much of a plot."}

In [49]:
pd.DataFrame(tokenized_dataset['train'])

,text,label,input_ids,attention_mask
0,I rented I AM CURIOUS-YELLOW from my video sto...,0,"[40, 48859, 358, 6769, 18548, 42652, 29137, 34...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
1,"""I Am Curious: Yellow"" is a risible and preten...",0,"[7044, 3303, 12886, 1223, 25, 25462, 1, 374, 2...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
2,If only to avoid making this type of film in t...,0,"[2679, 1172, 311, 5648, 3259, 419, 943, 315, 4...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
3,This film was probably inspired by Godard's Ma...,0,"[1986, 4531, 572, 4658, 14606, 553, 4264, 567,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
4,"Oh, brother...after hearing about this ridicul...",0,"[11908, 11, 10641, 1112, 10694, 10778, 911, 41...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
...,...,...,...,...
24995,A hit at the time but now better categorised a...,1,"[32, 4201, 518, 279, 882, 714, 1431, 2664, 220...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
24996,I love this movie like no other. Another time ...,1,"[40, 2948, 419, 5700, 1075, 902, 1008, 13, 132...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
24997,This film and it's sequel Barry Mckenzie holds...,1,"[1986, 4531, 323, 432, 594, 34761, 30758, 386,...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
24998,'The Adventures Of Barry McKenzie' started lif...,1,"[17323, 383, 50579, 4940, 30758, 92623, 6, 385...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."
24999,The story centers around Barry McKenzie who mu...,1,"[785, 3364, 18652, 2163, 30758, 92623, 879, 19...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ..."